name: 'Android Increment Version'
description: 'Increment your Android version code and version name'
branding:
  icon: arrow-up-circle
  color: orange
inputs:
  build-gradle-path:
    description: 'Path to your build.gradle file'
    required: false
    default: 'app/build.gradle'
  name-increment-type:
    description: 'Which type of version increment you want: Major|Minor|Patch'
    required: true
outputs:
  new-version-code:
    description: 'The newly incremented version code'
  new-version-name:
    description: 'The newly incremented version name'
runs:
  using: 'node24'
  main: 'dist/index.js'
